name: "🐛 Bug Report"
description: "File a bug report to help improve Chroma Explorer"
title: "[Bug]: "
labels: ["bug", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: versions
    attributes:
      label: Versions
      description: |
        What version of Chroma Explorer are you using? What OS are you on?
      placeholder: "Chroma Explorer v0.1.1, MacOS 14.0"
    validations:
      required: true

  - type: textarea
    id: chroma-version
    attributes:
      label: ChromaDB Version
      description: What version of ChromaDB are you connecting to?
      placeholder: "ChromaDB v0.4.0"
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false
